<?php

namespace Kostya1p\JwtAuth\tests\Unit;

use Kostya1p\JwtAuth\ExampleClass;
use PHPUnit\Framework\TestCase;

class ExampleClassTest extends TestCase
{
    public ExampleClass $example;

    protected function setUp(): void
    {
        $this->example = new ExampleClass();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testOne(): void
    {
        $this->example->setProperty('Hello');
        self::assertEquals('Hello', $this->example->getProperty());
    }
}
